### ISSUE TITLE
Installation on windows 10 failed

### ISSUE THREAD

**Issue by kimtang** [udacity/deep-reinforcement-learning#13]
Hello,

I followed the instruction and tried to install from the requirement.txt in python folder. But unfortunately I got the following error message. Can you please help to resolve?

Thanks,
Kim

(drlnd) deep-reinforcement-learning\python
> pip install .

Collecting torch==0.4.0 (from unityagents==0.4.0)
  Could not find a version that satisfies the requirement torch==0.4.0 (from unityagents==0.4.0) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch==0.4.0 (from unityagents==0.4.0)

**Comment by MNour10** [comment]
Hi Kimtang,

i have faced similar problem before and as i remember the problem was having higher version than the needed in the requirement.txt, so the solution either to install the elder version or change the requirement with the new version,
for me i have checked the difference between the two versions firstly before changing the requirement file

**Comment by kimtang** [comment]
Yes, pip has actually problem to install pytorch. So I deleted the line from requirements.txt and install it from anaconda. 

Dont really like to use two installation tool (anaconda and pip).

**Comment by kimtang** [comment]
Looks like it is really torch not pytorch. But installing it from pip or conda is not possible in windows.

**Comment by duhgrando** [comment]
I use windows 10 and I had the same problem. In my case, I installed pytorch via conda and removed it on requeriments.txt.

Steps:
1. Open deep-reinforcement-learning\python\requirements.txt
2. Remove the line 'torch==0.4.0'
**On Anaconda:
3. 'conda install pytorch=0.4.0 -c pytorch'
4. cd deep-reinforcement-learning/python
5. 'pip install .'
