### ISSUE TITLE
About Crawler for Continuous Control

### ISSUE THREAD

**Issue by ZeratuuLL** [udacity/deep-reinforcement-learning#16]
I am trying to solve the Crawler environment in Continuous control task. I have read the Unity webpage and realized that there were two environments. One with static target and one with dynamic target. Which one is provided through the links? Thank you!

**Comment by chihoxtra** [comment]
I too wanted to know the answer please.

**Comment by ZeratuuLL** [comment]
After some test it should be the fixed goal....

**Comment by chihoxtra** [comment]
I think so too. I was training my humble agent and it’s gaiining score and the visual shows that its always facing the same direction. I guess it is a fixed goal. Thanks man!

sam

**Comment by ZeratuuLL** [comment]
Np! What kind of results are you getting? The dimension info is different from Unity page so I am not sure if the benchmarks are still reliable.... I can get an average around 1800 but cannot get further....
  
  
  
 Lifeng Wei.  

  
From my phone and apology for any typos
  
  
  
  

  
  
>

**Comment by chihoxtra** [comment]
envy you! I have just started and I am trying to use PPO to solve the problem. I am only able to get to around 100 scores (average of rewards of pass 100 episodes across agents once any of the agent reached ‘done’). May I ask how many layers of network did you use?

**Comment by ZeratuuLL** [comment]
You can check my repo here. https://github.com/ZeratuuLL/Reinforcement-Learning/tree/master/Continuous%20Control/Crawler

It's not easy to say the structure directly....
