### ISSUE TITLE
SWIG required on windows for box2d

### ISSUE THREAD

**Issue by ivenzor** [udacity/deep-reinforcement-learning#2]
When installing Box2d it seems SWIG is a requirement on Windows.

After downloading SWIG and change windows path enviromental variable, Box2d was successfully installed.

**Comment by alexisbcook** [comment]
Thanks! I believe that OpenAI gym only officially supports Linux + Mac OSX (swig is listed as a requirement for those), so Windows users will find the instructions are a bit incomplete.  I'm really glad it worked for you without too much hassle.  You might also like to post your fix on this thread: https://github.com/openai/gym/issues/11

**Comment by ivenzor** [comment]
Thanks for the reference. I have just posted there what I did for Box2D.

I'm going to close this issue now.
