### ISSUE TITLE
OUNoise should use normal distribution

### ISSUE THREAD

**Issue by lukcn** [udacity/deep-reinforcement-learning#20]
The current implementation uses random.random() which I believe is uniform distribution between [0,1). This can negatively affect exploration abilities of DDPG agent, since noise will have positive bias.

**Comment by mojtabashokrian** [comment]
Let me add here that the [Wikipedia page](https://en.wikipedia.org/wiki/Ornstein%E2%80%93Uhlenbeck_process#Definition) also says that the second term in the sum defining the noise, which is supposed to be `dW_t=W_{t+1}-W_t` must be a [Wiener Process](https://en.wikipedia.org/wiki/Wiener_process#Characterisations_of_the_Wiener_process) which as mentioned in property 3 needs to have Gaussian increments, hence what @lukcn has referenced above.
