### ISSUE TITLE
In the bipedal walker, errors occur

### ISSUE THREAD

**Issue by BerrySG** [udacity/deep-reinforcement-learning#3]
File "c:\windows\system32\gym\gym\envs\box2d\bipedal_walker.py", line 383, in step
    self.joints[0].motorSpeed     = float(SPEED_HIP     * np.sign(action[0]))
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by crobarcro** [comment]
I see the same erro on Ubuntu 16.04. Somehow action becomes as array of arrays, so action[0] is actually an array of length 0.

**Comment by BerrySG** [comment]
@crobarcro 
I`ve solved the problem by reinstall the full version of OpenAI-GYM, it seems that some components are missing then lead to this problem

**Comment by BerrySG** [comment]
@crobarcro I download the whole source package then install

**Comment by pstansell** [comment]
@BerrySG, did you manage to run the notebook and get a policy that actually solves the walker problem?  I tried the fix of changing `action` to `action[0]`, which allowed the notebook to run, but it didn't produce useful policies (the walking just stumbles and falls over).  The graph of the score in the online notebook also suggests that the policies are not converging to a good solution like that displayed in the video in https://github.com/udacity/deep-reinforcement-learning/blob/master/ddpg-bipedal/README.md

**Comment by adipandas** [comment]
> @BerrySG, did you manage to run the notebook and get a policy that actually solves the walker problem? I tried the fix of changing `action` to `action[0]`, which allowed the notebook to run, but it didn't produce useful policies (the walking just stumbles and falls over). The graph of the score in the online notebook also suggests that the policies are not converging to a good solution like that displayed in the video in https://github.com/udacity/deep-reinforcement-learning/blob/master/ddpg-bipedal/README.md

There is some fault in the code I believe or may be DDPG is simply not able to solve the environment. I also tried to train it, it doesn't work.
I even tried to change the structure of the network and even tried to change the activation from relu to leaky_relu as suggested by @yoon-gu.
But results were no good. Will need to investigate more to find a feasible solution. Let me know, if anyone resolves it.

Thanks.
