### ISSUE TITLE
Banana.app Freezes on Mac

### ISSUE THREAD

**Issue by dcompgriff** [udacity/deep-reinforcement-learning#38]
Banana.app freezes when i've installed mlagents==0.4.0 when I try to run it from my Mac. Has anyone tried to run Banana.app on a Mac OS? I can't seem to get it working...

Mac Info:
  System Version:	macOS 10.13.6 (17G8030)
  Kernel Version:	Darwin 17.7.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal

**Comment by dcompgriff** [comment]
I figured it out. I didn't realize that I needed to keep running the other cells in the notebook to where the agent would start acting in the environment and it would be showing up.

**Comment by sysu-18364121** [comment]
hello
