### ISSUE TITLE
DDPG pendulum action scaling

### ISSUE THREAD

**Issue by IbrahimSobh** [udacity/deep-reinforcement-learning#41]
![Capture](https://user-images.githubusercontent.com/19908396/68516832-d9721c80-028d-11ea-96c6-15d5b440d442.PNG)
Hello 

In the file: deep-reinforcement-learning/ddpg-pendulum/DDPG.ipynb

In the [Pendulum-v0](https://github.com/openai/gym/wiki/Pendulum-v0) environment, the actions are in the range from -2.0 to +2.0
And hence, actions must be scaled before passing to the environment (the actor produces a tanh values from -1 to 1, limiting the agent to act properly)

```
action = agent.act(state)
action *= 2.0  # add this line of code
next_state, reward, done, _ = env.step(action)

```   
After I added this scaling factor, the agent converged much faster and even much better

Moreover, I used a simpler networks with only 32, 128 units instead of the 400 and 300.

Best Regards

**Comment by IbrahimSobh** [comment]
Hello 

Here are the testing results after applying the  proposed update above: 

Actions applied per time step: 
![a_t](https://user-images.githubusercontent.com/19908396/68518730-f14d9e80-0295-11ea-8f2e-f41312ee58fb.PNG)


Performance: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19908396/68518688-c400f080-0295-11ea-8f00-d066021a2474.gif)

**Comment by oliver1112** [comment]
I found the same problem.  After scaling the action value, I got a more faster convergance result and higher reward. Agents can get an average reward of about -150, while the original notebook shows about -300
