### ISSUE TITLE
C:\ProgramData\Anaconda3\envs\drlnd\python.exe: No module named ipykernel

### ISSUE THREAD

**Issue by Sdfabio** [udacity/deep-reinforcement-learning#50]
Hello everyone, 
I was following the tutorial to install ml agents, but when executing the line: 
**python -m ipykernel install --user --name drlnd --display-name "drlnd"**

I found Error :

**C:\ProgramData\Anaconda3\envs\drlnd\python.exe: No module named ipykernel**

I'm on windows 10 and I've installed anaconda 3 python 3.6

**Comment by PDillis** [comment]
You need to have ipykernel installed, so check out [the docs](https://ipython.readthedocs.io/en/stable/install/kernel_install.html).
