### ISSUE TITLE
AttributeError: module 'gym.envs.box2d' has no attribute 'LunarLander'

### ISSUE THREAD

**Issue by djahdkjqbwfkb1213** [udacity/deep-reinforcement-learning#54]
Thank u a lot for your program, and here is a problem i met when i ran the [deep-reinforcement-learning/dqn/solution/Deep_Q_Network_Solution.ipynb](https://github.com/udacity/deep-reinforcement-learning/blob/master/dqn/solution/Deep_Q_Network_Solution.ipynb) on the google colab platform.
![图片](https://user-images.githubusercontent.com/46812006/102461604-920ab200-4083-11eb-9836-31593e106f03.png)
as u can see, I cant make the env successfully.

**Comment by tawsifkamal** [comment]
Hey. You have to install the box2d module separately in order to get environments such as LunarLander to work. Here is a solution that you could consider: https://stackoverflow.com/questions/51811263/problems-pip-installing-box2d
