### ISSUE TITLE
Banana.exe Not working 

### ISSUE THREAD

**Issue by tawsifkamal** [udacity/deep-reinforcement-learning#59]
When trying to complete the p1_navigation project, I am not able to open the environment Banana.exe neither from Ubuntu 20.04 nor Windows 10. When I try to run the code cell listed below,

`env = UnityEnvironment(file_name="Banana_Windows_x86_64/Banana.exe")`

The error that I get is the following:

`timeout                                   Traceback (most recent call last)
~\anaconda3\envs\udacity_rl\lib\site-packages\unityagents\environment.py in __init__(self, file_name, worker_id, base_port, curriculum)
     98                 self._socket.listen(1)
---> 99                 self._conn, _ = self._socket.accept()
    100                 self._conn.settimeout(30)

~\anaconda3\envs\udacity_rl\lib\socket.py in accept(self)
    292         """
--> 293         fd, addr = self._accept()
    294         sock = socket(self.family, self.type, self.proto, fileno=fd)

timeout: timed out

During handling of the above exception, another exception occurred:

UnityTimeOutException                     Traceback (most recent call last)
<ipython-input-7-e80f4f4c1e22> in <module>
----> 1 env = UnityEnvironment(file_name="Banana_Windows_x86_64/Banana.exe")

~\anaconda3\envs\udacity_rl\lib\site-packages\unityagents\environment.py in __init__(self, file_name, worker_id, base_port, curriculum)
    102                 p = json.loads(p)
    103             except socket.timeout as e:
--> 104                 raise UnityTimeOutException(
    105                     "The Unity environment took too long to respond. Make sure {} does not need user interaction to "
    106                     "launch and that the Academy and the external Brain(s) are attached to objects in the Scene."

UnityTimeOutException: The Unity environment took too long to respond. Make sure Banana_Windows_x86_64/Banana does not need user interaction to launch and that the Academy and the external Brain(s) are attached to objects in the Scene.
`

Please help. Thank you.

**Comment by rajkk1** [comment]
Hello! What was the resolution to this problem?

**Comment by mikepratt1** [comment]
@rajkk1 did you find a solution to this?

**Comment by rajkk1** [comment]
> @rajkk1 did you find a solution to this?

No I don't think I ever did :/

**Comment by kethlenmedeiros2019-afk** [comment]
Banana exe
